In [1]:
import pandas as pd

In [6]:
team_stats=pd.read_csv("../DATA/team_stats.csv")

In [7]:
equip_no_rep=team_stats[team_stats['slug']
                     .isin([
                            'eng.burnley',
                            'eng.nottm_forest',
                            'eng.sheff_utd',
                            'eng.luton',
                            'fra.clermont_foot',
                            'esp.cadiz',
                            'esp.almeria',
                            'esp.granada_cf',
                            'ger.vfl_bochum',
                            'ger.1_fc_kln'
 ])]

In [8]:
equip_no_rep['slug'].value_counts()

slug
eng.luton            75
eng.sheff_utd        72
esp.almeria          68
eng.burnley          67
eng.nottm_forest     66
esp.cadiz            64
esp.granada_cf       64
ger.vfl_bochum       54
ger.1_fc_kln         53
fra.clermont_foot    51
Name: count, dtype: int64

In [10]:
equip_no_rep.to_csv("../DATA/equip_no_rep.csv",index=False)

### Análisis de valores atípicos

In [11]:
equip_no_rep.info()

<class 'pandas.core.frame.DataFrame'>
Index: 634 entries, 19346 to 102856
Data columns (total 36 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   teamId              634 non-null    int64
 1   abbreviation        634 non-null    object
 2   displayName         634 non-null    object
 3   slug                634 non-null    object
 4   seasonType          634 non-null    int64
 5   eventId             634 non-null    int64
 6   teamOrder           634 non-null    int64
 7   possessionPct       609 non-null    float64
 8   foulsCommitted      609 non-null    float64
 9   yellowCards         609 non-null    float64
 10  redCards            609 non-null    float64
 11  offsides            609 non-null    float64
 12  wonCorners          609 non-null    float64
 13  saves               609 non-null    float64
 14  totalShots          609 non-null    float64
 15  shotsOnTarget       609 non-null    float64
 16  shotPct             609 non-null    float64
 17  penaltyKickGoals    609 non-null    float64
 18  penaltyKickShots    609 non-null    float64
 19  accuratePasses      609 non-null    float64
 20  totalPasses         609 non-null    float64
 21  passPct             609 non-null    float64
 22  accurateCrosses     609 non-null    float64
 23  totalCrosses        609 non-null    float64
 24  crossPct            609 non-null    float64
 25  totalLongBalls      609 non-null    float64
 26  accurateLongBalls   609 non-null    float64
 27  longballPct         609 non-null    float64
 28  blockedShots        609 non-null    float64
 29  effectiveTackles    609 non-null    float64
 30  totalTackles        609 non-null    float64
 31  tacklePct           609 non-null    float64
 32  interceptions       609 non-null    float64
 33  effectiveClearance  609 non-null    float64
 34  totalClearance      609 non-null    float64
 35  updateTime          634 non-null    object
dtypes: float64(28), int64(4), object(4)
memory usage: 183.3+ KB

In [12]:
columns=['possessionPct',
       'foulsCommitted', 'yellowCards', 'redCards', 'offsides', 'wonCorners',
       'saves', 'totalShots', 'shotsOnTarget', 'shotPct', 'penaltyKickGoals',
       'penaltyKickShots', 'accuratePasses', 'totalPasses', 'passPct',
       'accurateCrosses', 'totalCrosses', 'crossPct', 'totalLongBalls',
       'accurateLongBalls', 'longballPct', 'blockedShots', 'effectiveTackles',
       'totalTackles', 'tacklePct', 'interceptions', 'effectiveClearance',
       'totalClearance']

In [13]:
summary_data = []

for col in columns:
    total_records = len(equip_no_rep[col])
    zero_count = (equip_no_rep[col] == 0).sum()
    nan_count = equip_no_rep[col].isna().sum()

    summary_data.append({
        'Column': col,
        'Total_Records': total_records,
        'Zero_Count': zero_count,
        'NaN_Count': nan_count,
        'Zero_or_NaN_Count': zero_count + nan_count
    })

summary_df = pd.DataFrame(summary_data)

In [14]:
summary_df

,Column,Total_Records,Zero_Count,NaN_Count,Zero_or_NaN_Count
0,possessionPct,634,1,25,26
1,foulsCommitted,634,3,25,28
2,yellowCards,634,71,25,96
3,redCards,634,555,25,580
4,offsides,634,360,25,385
5,wonCorners,634,17,25,42
6,saves,634,45,25,70
7,totalShots,634,1,25,26
8,shotsOnTarget,634,17,25,42
9,shotPct,634,18,25,43
10,penaltyKickGoals,634,548,25,573
11,penaltyKickShots,634,526,25,551
12,accuratePasses,634,299,25,324
13,totalPasses,634,299,25,324
14,passPct,634,299,25,324
15,accurateCrosses,634,309,25,334
16,totalCrosses,634,300,25,325
17,crossPct,634,311,25,336
18,totalLongBalls,634,300,25,325
19,accurateLongBalls,634,300,25,325
20,longballPct,634,300,25,325
21,blockedShots,634,48,25,73
22,effectiveTackles,634,302,25,327
23,totalTackles,634,301,25,326
24,tacklePct,634,302,25,327
25,interceptions,634,301,25,326
26,effectiveClearance,634,302,25,327
27,totalClearance,634,302,25,327

In [ ]:
cols_to_replace = [
    'possessionPct', 'foulsCommitted', 'accuratePasses', 'totalPasses', 'passPct',
    'totalLongBalls', 'accurateLongBalls', 'longballPct', 'effectiveTackles',
    'tacklePct', 'interceptions', 'effectiveClearance', 'totalClearance'
]

equip_no_rep = equip_no_rep.astype({col: 'float64' for col in cols_to_replace})

equip_no_rep = equip_no_rep.assign(
    **{
        col: equip_no_rep.groupby('slug')[col].transform(
            lambda x: x.where(x != 0, x[x != 0].mean())
        )
        for col in cols_to_replace
    }
)

In [19]:
summary_data_outliers = []

for col in columns:
    total_records = len(equip_no_rep[col])
    zero_count = (equip_no_rep[col] == 0).sum()
    nan_count = equip_no_rep[col].isna().sum()

    summary_data_outliers.append({
        'Column': col,
        'Total_Records': total_records,
        'Zero_Count': zero_count,
        'NaN_Count': nan_count,
        'Zero_or_NaN_Count': zero_count + nan_count
    })

summary_df_outliers = pd.DataFrame(summary_data_outliers)

In [20]:
summary_df_outliers

,Column,Total_Records,Zero_Count,NaN_Count,Zero_or_NaN_Count
0,possessionPct,634,0,25,25
1,foulsCommitted,634,0,25,25
2,yellowCards,634,71,25,96
3,redCards,634,555,25,580
4,offsides,634,360,25,385
5,wonCorners,634,17,25,42
6,saves,634,45,25,70
7,totalShots,634,1,25,26
8,shotsOnTarget,634,17,25,42
9,shotPct,634,18,25,43
10,penaltyKickGoals,634,548,25,573
11,penaltyKickShots,634,526,25,551
12,accuratePasses,634,0,25,25
13,totalPasses,634,0,25,25
14,passPct,634,0,25,25
15,accurateCrosses,634,309,25,334
16,totalCrosses,634,300,25,325
17,crossPct,634,311,25,336
18,totalLongBalls,634,0,25,25
19,accurateLongBalls,634,0,25,25
20,longballPct,634,0,25,25
21,blockedShots,634,48,25,73
22,effectiveTackles,634,0,25,25
23,totalTackles,634,301,25,326
24,tacklePct,634,0,25,25
25,interceptions,634,0,25,25
26,effectiveClearance,634,0,25,25
27,totalClearance,634,0,25,25

In [21]:
equip_no_rep_clean=equip_no_rep.dropna()

In [22]:
summary_data_clean = []

for col in columns:
    total_records = len(equip_no_rep[col])
    zero_count = (equip_no_rep_clean[col] == 0).sum()
    nan_count = equip_no_rep_clean[col].isna().sum()

    summary_data_clean.append({
        'Column': col,
        'Total_Records': total_records,
        'Zero_Count': zero_count,
        'NaN_Count': nan_count,
        'Zero_or_NaN_Count': zero_count + nan_count
    })

summary_df_clean = pd.DataFrame(summary_data_clean)

summary_df_clean

,Column,Total_Records,Zero_Count,NaN_Count,Zero_or_NaN_Count
0,possessionPct,634,0,0,0
1,foulsCommitted,634,0,0,0
2,yellowCards,634,71,0,71
3,redCards,634,555,0,555
4,offsides,634,360,0,360
5,wonCorners,634,17,0,17
6,saves,634,45,0,45
7,totalShots,634,1,0,1
8,shotsOnTarget,634,17,0,17
9,shotPct,634,18,0,18
10,penaltyKickGoals,634,548,0,548
11,penaltyKickShots,634,526,0,526
12,accuratePasses,634,0,0,0
13,totalPasses,634,0,0,0
14,passPct,634,0,0,0
15,accurateCrosses,634,309,0,309
16,totalCrosses,634,300,0,300
17,crossPct,634,311,0,311
18,totalLongBalls,634,0,0,0
19,accurateLongBalls,634,0,0,0
20,longballPct,634,0,0,0
21,blockedShots,634,48,0,48
22,effectiveTackles,634,0,0,0
23,totalTackles,634,301,0,301
24,tacklePct,634,0,0,0
25,interceptions,634,0,0,0
26,effectiveClearance,634,0,0,0
27,totalClearance,634,0,0,0

In [23]:
equip_no_rep_clean["slug"].value_counts()

slug
eng.sheff_utd        71
eng.luton            67
esp.almeria          66
eng.burnley          65
eng.nottm_forest     64
esp.granada_cf       62
esp.cadiz            61
ger.1_fc_kln         51
ger.vfl_bochum       51
fra.clermont_foot    51
Name: count, dtype: int64

In [24]:
equip_no_rep_clean.to_csv("../DATA/equip_no_rep_clean.csv",index=False)